version: '3.4'

services:
  myblogsapp:
    image: ${DOCKER_REGISTRY-}myblogsapp
    build:
      context: .
      dockerfile: MyBlogsApp/Dockerfile
    ports: 
      - "8080:8080"
      - "8081:8081"
    depends_on: 
      - sqlserver
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MyBlogsAppDb2;User Id=sa;Password=Teamwork@1;TrustServerCertificate=True;
      - Redis__Configuration=redis:6379
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Teamwork@1"
      ACCEPT_EULA: "Y"
    ports:
      - "1401:1433"
  redis:
    image: "redis:latest"
    ports:
      - "6380:6379" 










